### ISSUE TITLE
not compatible with unity

### ISSUE THREAD

**Issue by delmarle** [mwage/DarkRift2_Boilerplate#3]
when i import it into unity 2017.3 i have errors:

Feature `null propagating operator' cannot be used because it is not part of the C# 4.0 language specification

**Comment by mwage** [comment]
Haven't updated Unity in a while, but that sounds like you're using .NET 3.5 instead of 4.6. Try setting it to 4.6 in in Project Settings -> Player -> Scripting Runtime Version. DarkRift required 4.6 for some things, dunno if that's still the cause, would need to ask Jamie about it. 

If above doesn't work, let me know. Alternatively, if you don't want to use 4.6, you could replace every "x?.y; with "if (x != null) { x.y; }. That does the exact same thing, it's just more verbose.
